lab 1 initial commit
alinaguselnikova/OOP pull request #1
Opened 2021-09-30 08:17 UTC by alinaguselnikova

2021-09-30 11:25 UTC, molo4evan requested changes

2021-09-30 11:25 UTC, molo4evan commented on Task_1_1_1/src/test/java/nsu/fit/Tests.java
> +        int[] sorted = {0, 2, 3, 6, 7};
1. Не стоит вводить отсортированную версию руками, можно ошибиться. Лучше скопировать и отсортировать стандартными средствами изначальный массив (см. `Arrays`)
2. Тесты однотипные, можно заменить 1 parameterized тестом (см. гайд в гисте)
3. А если передадут `null`?

2021-09-30 11:25 UTC, molo4evan commented on Task_1_1_1/src/main/java/ru/nsu/fit/HeapSort.java
> +//Создаём единственный публичный класс Heapsort
Нужны javadocs

2021-09-30 11:25 UTC, molo4evan commented on Task_1_1_1/src/main/java/ru/nsu/fit/HeapSort.java
> +    //Создаём конструктор Heapsort
Нужны javadocs

2021-09-30 11:25 UTC, molo4evan commented on Task_1_1_1/src/main/java/ru/nsu/fit/HeapSort.java
> +    //Создаём публичный метод sort, не возвращающий ничего и работающий с массивом
Нужны javadocs

2021-09-30 11:25 UTC, molo4evan commented on Task_1_1_1/src/test/java/nsu/fit/Tests.java
> +        HeapSort a = new HeapSort(n);
А почему `a`?

2021-09-30 11:25 UTC, molo4evan commented on Task_1_1_1/src/main/java/ru/nsu/fit/HeapSort.java
> +    void heap(int[] arr, int n, int i) {
`private`

2021-09-30 11:25 UTC, molo4evan commented on Task_1_1_1/src/main/java/ru/nsu/fit/HeapSort.java
> +     public void sort(int[] arr) {
А если размер массива больше, чем `n` хипсорта?

2021-09-30 11:25 UTC, molo4evan commented on Task_1_1_1/src/main/java/ru/nsu/fit/HeapSort.java
> +    int[] heap;
`private`

2021-09-30 11:25 UTC, molo4evan commented on Task_1_1_1/src/main/java/ru/nsu/fit/HeapSort.java
> +            int c = arr[0];
Swap есть в 2 местах, вынеси в функцию (несущественно, но можешь считать придиркой)

2021-09-30 11:25 UTC, molo4evan commented on Task_1_1_1/src/main/java/ru/nsu/fit/HeapSort.java
> +    int[] heap;
Имеет право на жизнь, но, вообще, можно же реализовать heapsort и без выделения доп. памяти

2021-10-03 09:19 UTC, alinaguselnikova commented on Task_1_1_1/src/test/java/nsu/fit/Tests.java
> +        int[] sorted = {0, 2, 3, 6, 7};
Исправила

2021-10-03 09:19 UTC, alinaguselnikova commented on Task_1_1_1/src/main/java/ru/nsu/fit/HeapSort.java
> +//Создаём единственный публичный класс Heapsort
Сделала

2021-10-03 09:20 UTC, alinaguselnikova commented on Task_1_1_1/src/test/java/nsu/fit/Tests.java
> +        HeapSort a = new HeapSort(n);
Удалила эту строчку кода

2021-10-03 09:21 UTC, alinaguselnikova commented on Task_1_1_1/src/main/java/ru/nsu/fit/HeapSort.java
> +    void heap(int[] arr, int n, int i) {
Для создания TestNull мне пришлось сделать все методы ещё и static. Сильно критично?

2021-10-08 05:06 UTC, molo4evan commented on Task_1_1_1/src/test/java/nsu/fit/Tests.java
> +        }
Отступы поплыли

2021-10-08 05:06 UTC, molo4evan commented on Task_1_1_1/src/test/java/nsu/fit/Tests.java
> +    @ParameterizedTest
Методы разделяются пустой строкой

2021-10-08 05:06 UTC, molo4evan commented on Task_1_1_1/src/test/java/nsu/fit/Tests.java
> +    }
Отступы поплыли x2

2021-10-08 05:06 UTC, molo4evan commented on Task_1_1_1/src/test/java/nsu/fit/Tests.java
> +public class Tests {
Можешь просто сделать `Ctrl+Alt+L` для форматирования

2021-10-08 05:06 UTC, molo4evan commented on Task_1_1_1/src/main/java/ru/nsu/fit/HeapSort.java
> +    void heap(int[] arr, int n, int i) {
В целом - нет

2021-10-15 07:23 UTC, merged